version: '3'

services:
 mysql:
   image: mysql
   environment:
    MYSQL_DATABASE: 'projetppe'
    MYSQL_ROOT_PASSWORD: ppegroupe2

 phpmyadmin:
  image: phpmyadmin
  depends_on:
    - mysql
  ports: 
    - 8081:80
  environment:
    PMA_HOST: mysql
    PMA_PORT: 3306
    UPLOAD_LIMIT: 64M
 apachephp:
    build:
      apachephp
    ports:
      - 8002:80
    volumes:
      - ./apachephp/vhosts:/etc/apache2/sites-enabled
      - ./app:/var/www